{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
{{- end }}