apiVersion: v1
kind: Secret
metadata:
name: django-secret
type: Opaque
stringData:
    DJANGO_SECRET_KEY: {{ .Values.app.secretKey | quote }}
    DATABASE_NAME: {{ .Values.postgres.database | quote }}
    DATABASE_USERNAME: {{ .Values.postgres.username | quote }}
    DATABASE_PASSWORD: {{ .Values.postgres.password | quote }}